spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jbo
    username: root
    password: Jbo20030322


mybatis:
  configuration:
    map-underscore-to-camel-case: true

